### PR TITLE
Simplify this action

### PR DESCRIPTION
**Pull request by jspiro**
While I appreciate the intent of the functionality you included upfront, it made it really hard to use this action generically and broadly. I've simplified it to Just Work–scanning the entire repo for schemas and reporting what it finds. Targeting individual files doesn't scale.

If this isn't what you want, I can publish my work to GitHub Actions Marketplace, but I thought I'd give you the option ahead of time.

### CODE REVIEW

**Comment by stigok** [comment]
Hello! Thanks for your interest. This does not feel like what we want, because
- you are no longer in control of where to put your schema file(s), but leave it up to _Yamale_'s implementation to find them. In your use-cases there might be a single schema file per repo, but we have cases where we have multiple targets with different schemas.
- you have removed `error_is_success`, which breaks the automated tests for this action.
- you have removed `str_bool` which normalises the input values when e.g. the input value is missing.

Feel free to create your own fork and publish it freely within the limitations of the license :)

**Comment by jspiro** [comment]
Thanks for the thoughtful review and response. Even if we end up in the same place, I wanted to respond and explain why I did it this way, for anyone that reads this!

Correct, given your versioning scheme to match Yamale, it seemed appropriate to tie the functionality of a particular version to the implementation.

Your version requires every schema to be pre-identified and hard-coded in the Action (if I understood the intended use correctly) a-priori. The thinking here is that Yamale discovers every single schema in the repo automagically, which scales better with teams adding schemas and not needing to know that they have to edit an action to enable them.

This version will auto-discover all schemas and report success or failure, which is pretty simple. I couldn't find a way to support this in your version.

Anyway, thanks for building this. If you have any ideas how to update your own to support our simple use case, I'd be happy to help with it so we only have one version in the marketplace.

**Comment by stigok** [comment]
I'll keep this in mind. It probably won't bubble up until we have a similar problem as you.

> Anyway, thanks for building this. If you have any ideas how to update your own to support our simple use case, I'd be happy to help with it so we only have one version in the marketplace.

Actually, this repository will never land in the marketplace under this organisation due to legal issues with the GitHub Marketplace terms of use.

**Comment by jspiro** [comment]
@stigok To clarify, this is MIT license–are there legal issues I should be aware of that are incompatible with your license file, or is it a personal issue with their TOS?

**Comment by jspiro** [comment]
I thought I discovered this via the Marketplace, but I must be mistaken.

**Comment by stigok** [comment]
It's a legal issue with the ToS for the organisation this repository is hosted under. Unless someone clicked the wrong button, it shouldn't have been published there, at least :) This repo is only covered under MIT license, indeed.

**Pull request closed without merging**
